name: Mandatory Approvals

on:
  pull_request_review:
    types: [submitted]

jobs:
  approved:
    if: github.event.review.state == 'approved' && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-22.04

    steps:
      - name: Mandatory Approvals
        run: |
          approvers=$(curl -Lfs \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.COGOPORT_DEV_ADMIN_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews | jq -r '[ .[] | select(.state == "APPROVED") | .user.login ] | unique | .[]')

          members=$(curl -Lfs \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.COGOPORT_DEV_ADMIN_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/orgs/Cogoport/teams/platform-engineering/members | jq -rc '[ .[] | .login ]')

          for approver in $(echo $approvers)
          do
            if echo $members | grep $approver; then
              exit 0
            fi
          done

          exit 1
